# -*- coding: utf-8 -*-
"""Write the professor list into its HTML at build time.

The page held 2,640 faculty, every one read from their own bio page, and
shipped 1,365 characters of visible text: a search box and "Loading
professors...". Every name arrived by JavaScript after load, so as far as
search was concerned none of them existed -- on the page most likely to be
searched for by name. It is the same problem the tracker had, on five times
as many names.

Two decisions worth knowing about, because both were measured rather than
assumed:

  Interests are not pre-rendered. With them the block is 268KB gzipped; with
  names, school and program alone it is 108KB, which is the tracker's 79KB in
  the same ballpark. The names are what people search; the interests are what
  the search box filters on and stay in the JSON for it. Topic pages are the
  right place for interests as crawlable text, because there they are grouped
  by subject instead of scattered across 2,640 cards.

  The accepting/not-accepting badge is not pre-rendered either. Resolving a
  program's list of names to a professor record needs the fuzzy matcher in
  js/professor-search.js -- "Denise Chavira" on the program page against
  "Denise A. Chavira" here -- and an exact-match version of it in Python
  resolved only 78%, which would have silently shown 111 accepting professors
  as unknown and disagreed with what the script renders a moment later. The
  tracker already carries that status as crawlable text; each card here links
  to the right entry on it instead, so the answer is one click away and stated
  in one place.

Called from build.py. Safe to re-run: it replaces everything between the
markers.
"""
import html
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
DATA = os.path.join(SITE, "data", "professors.json")
PROGRAMS = os.path.join(SITE, "data", "programs.json")
PAGE = os.path.join(SITE, "tools", "professor-search.html")

START = "<!-- professors:list start (generated by scripts/render_professors.py) -->"
END = "<!-- professors:list end -->"


def e(s):
    return html.escape(str(s if s is not None else ""), quote=True)


def card(p, program_id):
    # The tracker link is worth its bytes and the interests are not: measured
    # over all 2,640 cards, the link costs 18KB gzipped because the same URL
    # shape repeats and compresses away, while three interests per card cost
    # 120KB because every one is different prose.
    tracker = (f'<a class="prof-tracker-link" '
               f'href="faculty-accepting-students.html#program-{e(program_id)}">'
               f'Accepting-students status &rarr;</a>' if program_id else "")
    return (
        f'<li class="fac-card" id="prof-{e(p["id"])}">'
        '<div class="fac-head"><div>'
        f'<h3>{e(p["name"])}</h3>'
        f'<p class="fac-sub">{e(p["school"])} &middot; {e(p["program"])}</p>'
        '</div></div>'
        '<div class="fac-foot">'
        f'<a href="{e(p.get("url"))}" target="_blank" rel="noopener">'
        'View their university page &rarr;</a>'
        f'{tracker}</div></li>'
    )


def replace_between(text, payload):
    if START in text and END in text:
        return (text.split(START)[0] + START + payload + END
                + text.split(END, 1)[1])
    placeholder = re.search(
        r'([ \t]*)<li class="fac-empty">Loading professors[^<]*</li>', text)
    if not placeholder:
        raise SystemExit("render_professors: could not find the list "
                         "placeholder or the markers in " + PAGE)
    indent = placeholder.group(1)
    return text.replace(placeholder.group(0),
                        f"{indent}{START}{payload}{indent}{END}")


def render():
    data = json.load(open(DATA, encoding="utf-8"))
    professors = sorted(data["professors"], key=lambda p: p["name"].lower())

    programs = json.load(open(PROGRAMS, encoding="utf-8"))["programs"]
    program_id = {(p["school"], p["program"]): p["id"] for p in programs}

    cards, linked = [], 0
    for p in professors:
        pid = program_id.get((p["school"], p["program"]))
        linked += bool(pid)
        cards.append(card(p, pid))

    text = open(PAGE, encoding="utf-8").read()
    text = replace_between(text, "\n" + "\n".join(cards) + "\n")

    schools = len({p["school"] for p in professors})
    stats = (f'<strong>{len(professors)}</strong> professors across '
             f'<strong>{schools}</strong> programs &middot; last updated '
             f'{e(data.get("updated", ""))}')
    text = re.sub(r'(<p class="fac-stats" id="prof-stats">).*?(</p>)',
                  lambda m: m.group(1) + stats + m.group(2),
                  text, count=1, flags=re.S)

    open(PAGE, "w", encoding="utf-8").write(text)
    return {"professors": len(professors), "schools": schools, "linked": linked}


if __name__ == "__main__":
    r = render()
    print(f"professors pre-rendered: {r['professors']} across {r['schools']} "
          f"programs, {r['linked']} linked to a tracker entry")
