# -*- coding: utf-8 -*-
"""Write the accepting-students tracker into its HTML at build time.

The page used to ship as an empty shell -- 10KB of navigation and a
"Loading programs..." placeholder -- with every program, professor and
university injected by JavaScript after load. Crawlers index the served
HTML, so none of the 500-odd faculty names or 257 programs existed as far
as search was concerned, on the one page most likely to be searched for by
name ("is <professor> accepting students").

This renders the same cards the JavaScript renders, into the file. The
script still takes over on load for filtering, search and the star
buttons, so behaviour is unchanged; the difference is that the names are
in the document before any script runs.

Called from build.py. Safe to re-run: it replaces everything between the
marker comments.
"""
import html
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
DATA = os.path.join(SITE, "data", "programs.json")
PAGE = os.path.join(SITE, "tools", "faculty-accepting-students.html")

START = "<!-- tracker:list start (generated by scripts/render_tracker.py) -->"
END = "<!-- tracker:list end -->"

STATUS_LABEL = {
    "posted": "List posted",
    "pending": "Not posted yet",
    "unverified": "Not checked by us yet",
    "cohort": "Admits by cohort — no mentor list",
    "closed": "Program closed this cycle",
}
GRE_LABEL = {
    "required": "GRE: required",
    "optional": "GRE: optional",
    "not required": "GRE: not required",
    "not considered": "GRE: not considered",
    "not mentioned": "GRE: not stated",
}


def e(s):
    return html.escape(str(s if s is not None else ""), quote=True)


def app_info(p):
    items = []
    if p.get("applicationDeadline"):
        sub = (f' <span class="fac-appinfo-sub">({e(p["deadlineCycle"])})</span>'
               if p.get("deadlineCycle") else "")
        items.append('<span class="fac-appinfo-item">Deadline: '
                     f'<strong>{e(p["applicationDeadline"])}</strong>{sub}</span>')
    gre = GRE_LABEL.get(p.get("greRequired"))
    if gre:
        items.append(f'<span class="fac-appinfo-item">{e(gre)}</span>')
    if p.get("numReferences"):
        n = p["numReferences"]
        items.append(f'<span class="fac-appinfo-item">{n} reference'
                     f'{"" if n == 1 else "s"}</span>')
    if p.get("applicationFee"):
        items.append(f'<span class="fac-appinfo-item">Fee: {e(p["applicationFee"])}</span>')

    other = p.get("otherRequirements") or []
    other_html = ('<ul class="fac-appinfo-other">'
                  + "".join(f"<li>{e(r)}</li>" for r in other)
                  + "</ul>") if other else ""
    if not items and not other_html:
        return ""
    row = f'<div class="fac-appinfo-row">{"".join(items)}</div>' if items else ""
    return f'<div class="fac-appinfo">{row}{other_html}</div>'


def name_list(names, cls, label):
    """Names only. The per-professor star buttons need the professors file and
    the fuzzy name matcher, so the script adds those on load; what matters here
    is that the names themselves are in the document."""
    if not names:
        return ""
    lis = "".join(f'<li class="{cls}">{e(n)}</li>' for n in names)
    return (f'<div class="fac-group"><p class="fac-group-label {cls}">{label}</p>'
            f'<ul class="fac-names">{lis}</ul></div>')


def star_button(p):
    return ('<button type="button" class="star-btn" '
            f'data-star-school="{e(p["id"])}" aria-pressed="false" '
            'aria-label="Save to my list" title="Save to my list">☆</button>')


def card(p):
    if p["status"] == "posted":
        badge = ('<span class="fac-badge posted">'
                 f'{len(p.get("accepting") or [])} accepting</span>')
    else:
        badge = (f'<span class="fac-badge {e(p["status"])}">'
                 f'{e(STATUS_LABEL.get(p["status"], ""))}</span>')

    sub = e(p["program"])
    if p.get("state"):
        sub += " · " + e(p["state"])
    if p.get("pcsas"):
        sub += (' · <span class="fac-pcsas" title="Accredited by the Psychological '
                'Clinical Science Accreditation System">PCSAS accredited</span>')

    note = f'<p class="fac-note">{e(p["note"])}</p>' if p.get("note") else ""
    quote = (f'<p class="fac-quote">“{e(p["sourceQuote"])}”</p>'
             if p.get("sourceQuote") else "")
    checked = (f'<span class="fac-checked">Checked {e(p["checked"])}</span>'
               if p.get("checked") else "")

    # id gives every program a direct anchor, so a search that lands on this
    # page can be pointed at the right entry
    return (
        f'<li class="fac-card" id="program-{e(p["id"])}">'
        '<div class="fac-head"><div>'
        f'<h3>{e(p["school"])}</h3>'
        f'<p class="fac-sub">{sub}</p>'
        '</div>'
        f'<div class="fac-head-right">{star_button(p)}{badge}</div>'
        '</div>'
        + app_info(p)
        + name_list(p.get("accepting"), "yes", "Accepting students")
        + name_list(p.get("maybe"), "maybe", "Undecided — contact directly")
        + name_list(p.get("notAccepting"), "no", "Not accepting this cycle")
        + note + quote
        + '<div class="fac-foot">'
        f'<a href="{e(p.get("url"))}" target="_blank" rel="noopener">'
        'Check the program’s own page →</a>'
        f'{checked}</div></li>'
    )


def replace_between(text, start, end, payload):
    if start in text and end in text:
        pre = text.split(start)[0]
        post = text.split(end, 1)[1]
        return pre + start + payload + end + post
    # first run: swap the loading placeholder for the generated block
    placeholder = re.search(
        r'([ \t]*)<li class="fac-empty">Loading programs[^<]*</li>', text)
    if not placeholder:
        raise SystemExit("render_tracker: could not find the list placeholder "
                         "or the markers in " + PAGE)
    indent = placeholder.group(1)
    return text.replace(placeholder.group(0),
                        f"{indent}{start}{payload}{indent}{end}")


# The cycle year appears in the title, the H1, the visible heading and the
# social cards. Retyping it in five places once a year is how a tracker ends
# up advertising last cycle, so it is written from programs.json instead --
# which keeps the brief's rule that this page keeps one URL forever and only
# the year changes.
CYCLE = re.compile(r"Fall\s+\d{4}")
CYCLE_ELEMENTS = [
    r"(<title>)(.*?)(</title>)",
    r"(<meta name=\"description\" content=\")(.*?)(\">)",
    r"(<meta property=\"og:title\" content=\")(.*?)(\">)",
    r"(<meta property=\"og:description\" content=\")(.*?)(\">)",
    r"(<h1 class=\"visually-hidden\">)(.*?)(</h1>)",
    r"(<h2>Who's Accepting Doctoral Students)(.*?)(</h2>)",
]


def set_cycle(text, cycle):
    if not CYCLE.fullmatch(cycle or ""):
        return text  # an unexpected cycle string is left alone rather than guessed at
    for pat in CYCLE_ELEMENTS:
        text = re.sub(pat,
                      lambda m: m.group(1) + CYCLE.sub(cycle, m.group(2)) + m.group(3),
                      text, count=1, flags=re.S)
    # the lede's cycle, which the script also fills in on load
    return re.sub(r'(<(?:span|strong|em|b)[^>]*id="fac-cycle"[^>]*>).*?(</(?:span|strong|em|b)>)',
                  lambda m: m.group(1) + e(cycle) + m.group(2), text, count=1, flags=re.S)


def render():
    data = json.load(open(DATA, encoding="utf-8"))
    programs = sorted(data["programs"], key=lambda p: p["school"].lower())
    posted = [p for p in programs if p["status"] == "posted"]
    faculty = sum(len(p.get("accepting") or []) for p in posted)

    text = open(PAGE, encoding="utf-8").read()
    cards = "\n" + "\n".join(card(p) for p in programs) + "\n"
    text = replace_between(text, START, END, cards)
    text = set_cycle(text, data.get("cycle", ""))

    # the same three lines the script fills in on load, so they are also
    # present for a crawler that never runs it
    stats = (f'<strong>{faculty}</strong> faculty confirmed accepting across '
             f'<strong>{len(posted)}</strong> programs · last updated '
             f'{e(data.get("updated", ""))}')
    text = re.sub(r'(<p class="fac-stats" id="fac-stats">).*?(</p>)',
                  lambda m: m.group(1) + stats + m.group(2), text, count=1, flags=re.S)

    showing = f"Showing {len(programs)} of {len(programs)} programs checked so far"
    text = re.sub(r'(<p class="fac-showing" id="fac-showing">).*?(</p>)',
                  lambda m: m.group(1) + showing + m.group(2), text, count=1, flags=re.S)

    new = sorted((p["school"] for p in programs if p.get("newlyPosted")), key=str.lower)
    if new:
        text = re.sub(r'(<div class="fac-new-banner" id="fac-new-banner")\s+hidden(>)',
                      r"\1\2", text, count=1)
        text = re.sub(r'(<span id="fac-new-schools">).*?(</span>)',
                      lambda m: m.group(1) + e(", ".join(new)) + m.group(2),
                      text, count=1, flags=re.S)

    open(PAGE, "w", encoding="utf-8").write(text)
    return {"programs": len(programs), "posted": len(posted), "faculty": faculty,
            "newly": len(new)}


if __name__ == "__main__":
    r = render()
    print(f"tracker pre-rendered: {r['programs']} programs, "
          f"{r['faculty']} faculty across {r['posted']} posted")
