# -*- coding: utf-8 -*-
"""Write the extensionless -> .html redirect rules into _redirects.

Turning off Netlify's Pretty URLs stopped the site *linking* to extensionless
URLs, but Netlify still *serves* them: /research and /research.html both
returned 200, with no redirect between them. Every page was reachable at two
addresses. The canonical tags make it unambiguous which one to index, so this
is a loose end rather than a fire -- but an external link to a bare URL still
gets crawled at the non-canonical address, and this closes that.

Why every rule is an exact path and not a wildcard: the obvious rule,

    /studies/*  /studies/:splat.html  301!

also matches /studies/foo.html and sends it to /studies/foo.html.html, because
Netlify's splat has no way to exclude paths that already end in .html. Exact
paths cannot over-match or loop, and there are only ~75 of them, so they are
generated here from the same page list scripts/check_canonicals.py walks. Add a
page and its rule appears; delete one and its rule goes.

Rules are forced (301!) so they beat Netlify's built-in clean-URL file serving,
which is the thing answering those requests today.

Called from build.py. Safe to re-run: it replaces everything between the
markers and leaves the hand-written rules above them alone.
"""
import os

import check_canonicals

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
FILE = os.path.join(SITE, "_redirects")

START = "# --- generated by scripts/render_redirects.py: do not edit below ---"
END = "# --- end generated ---"


def rules():
    """One rule per page, in path order so a diff is readable."""
    out = []
    for rel in sorted(check_canonicals.pages()):
        if rel == "index.html":
            # /index.html is the same page as /. The bare "/" request never
            # matches this rule, so there is nothing to loop on.
            out.append(("/index.html", "/"))
        elif rel.endswith("/index.html"):
            directory = "/" + rel[: -len("index.html")]
            out.append(("/" + rel, directory))
        else:
            out.append(("/" + rel[: -len(".html")], "/" + rel))
    return out


def render():
    text = open(FILE, encoding="utf-8").read()

    pairs = rules()
    # Deliberately not column-aligned. Padding to the longest source means one
    # new page with a long slug reflows every line in the diff.
    body = "\n".join(f"{src}  {dst}  301!" for src, dst in pairs)
    block = (
        f"{START}\n"
        "# Extensionless URLs and /index.html both resolve to a real page on\n"
        "# Netlify, which meant every page answered at two addresses. These send\n"
        "# the duplicate to the canonical one.\n"
        f"{body}\n"
        f"{END}"
    )

    if START in text and END in text:
        pre = text.split(START)[0]
        post = text.split(END, 1)[1]
        text = pre + block + post
    else:
        text = text.rstrip("\n") + "\n\n" + block + "\n"

    open(FILE, "w", encoding="utf-8").write(text)
    return len(pairs)


if __name__ == "__main__":
    print(f"_redirects: {render()} extensionless rules written")
