# -*- coding: utf-8 -*-
"""Write the accepting-students tracker into its HTML at build time.

The page used to ship as an empty shell -- 10KB of navigation and a
"Loading programs..." placeholder -- with every program, professor and
university injected by JavaScript after load. Crawlers index the served
HTML, so none of the 500-odd faculty names or 257 programs existed as far
as search was concerned, on the one page most likely to be searched for by
name ("is <professor> accepting students").

This renders the same cards the JavaScript renders, into the file. The
script still takes over on load for filtering, search and the star
buttons, so behaviour is unchanged; the difference is that the names are
in the document before any script runs.

Called from build.py. Safe to re-run: it replaces everything between the
marker comments.
"""
import confirmed
import deadline as deadline_mod
import html
import json
import os
import re
from datetime import date, timedelta

# How long a posting counts as news. "Newly posted" next to a last-updated date
# of today implied these programs had posted today, when four of them had done
# it six days earlier -- so each flag carries the date it was set, and drops out
# of the banner on its own once it is this old. Nothing to remember to clear.
NEWLY_WINDOW_DAYS = 21

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
DATA = os.path.join(SITE, "data", "programs.json")
PAGE = os.path.join(SITE, "tools", "faculty-accepting-students.html")

START = "<!-- tracker:list start (generated by scripts/render_tracker.py) -->"
END = "<!-- tracker:list end -->"

STATUS_LABEL = {
    "posted": "List posted",
    "pending": "Not posted yet",
    "unverified": "Not checked by us yet",
    "cohort": "Admits by cohort — no mentor list",
    "closed": "Program closed this cycle",
}
GRE_LABEL = {
    "required": "GRE: required",
    "optional": "GRE: optional",
    "not required": "GRE: not required",
    "not considered": "GRE: not considered",
    "not mentioned": "GRE: not stated",
}


def e(s):
    return html.escape(str(s if s is not None else ""), quote=True)


def app_info(p):
    items = []
    if p.get("applicationDeadline"):
        sub = (f' <span class="fac-appinfo-sub">({e(p["deadlineCycle"])})</span>'
               if p.get("deadlineCycle") else "")
        items.append('<span class="fac-appinfo-item">Deadline: '
                     f'<strong>{e(deadline_mod.resolve(p)[0])}</strong>'
                     f'{sub}</span>')
    gre = GRE_LABEL.get(p.get("greRequired"))
    if gre:
        items.append(f'<span class="fac-appinfo-item">{e(gre)}</span>')
    if p.get("numReferences"):
        n = p["numReferences"]
        items.append(f'<span class="fac-appinfo-item">{n} reference'
                     f'{"" if n == 1 else "s"}</span>')
    if p.get("applicationFee"):
        items.append(f'<span class="fac-appinfo-item">Fee: {e(p["applicationFee"])}</span>')

    other = p.get("otherRequirements") or []
    other_html = ('<ul class="fac-appinfo-other">'
                  + "".join(f"<li>{e(r)}</li>" for r in other)
                  + "</ul>") if other else ""
    if not items and not other_html:
        return ""
    row = f'<div class="fac-appinfo-row">{"".join(items)}</div>' if items else ""
    return f'<div class="fac-appinfo">{row}{other_html}</div>'


def name_list(names, cls, label):
    """Names only. The per-professor star buttons need the professors file and
    the fuzzy name matcher, so the script adds those on load; what matters here
    is that the names themselves are in the document."""
    if not names:
        return ""
    lis = "".join(f'<li class="{cls}">{e(n)}</li>' for n in names)
    return (f'<div class="fac-group"><p class="fac-group-label {cls}">{label}</p>'
            f'<ul class="fac-names">{lis}</ul></div>')


def star_button(p):
    return ('<button type="button" class="star-btn" '
            f'data-star-school="{e(p["id"])}" aria-pressed="false" '
            'aria-label="Save to my list" title="Save to my list">☆</button>')


def watch_button(p):
    """Always written in the off state, and omitted where there is nothing
    left to wait for.

    Whether someone is watching a program is a fact about one person, and this
    file is one document served to everybody and cached by crawlers. Baking in
    a real state would show the first visitor's choices to the next one.
    js/faculty.js corrects it on load once it knows who is asking -- the same
    reason the star ships un-starred.

    Which is also why a program whose list is already posted gets no button
    here even if somebody is watching it: this file cannot know that. The
    script puts it back for that person, so they can still switch it off."""
    if p["status"] in ("posted", "closed"):
        return ""
    return ('<button type="button" class="watch-btn" '
            f'data-watch-school="{e(p["id"])}" aria-pressed="false" '
            'title="Tell me when this program changes">'
            '<span aria-hidden="true">🔔</span> '
            '<span class="watch-btn-text">Notify me</span></button>')


def card(p):
    if p["status"] == "posted":
        n = len(p.get("accepting") or [])
        m = len(p.get("maybe") or [])
        # "0 accepting" beside six names listed as considering applications is
        # true of the accepting column and wrong about the program. Count what
        # the card actually goes on to show.
        badge = ('<span class="fac-badge posted">'
                 f'{n} accepting</span>' if n or not m else
                 '<span class="fac-badge posted">'
                 f'{m} considering</span>')
    else:
        badge = (f'<span class="fac-badge {e(p["status"])}">'
                 f'{e(STATUS_LABEL.get(p["status"], ""))}</span>')

    sub = e(p["program"])
    if p.get("state"):
        sub += " · " + e(p["state"])
    if p.get("pcsas"):
        sub += (' · <span class="fac-pcsas" title="Accredited by the Psychological '
                'Clinical Science Accreditation System">PCSAS accredited</span>')

    # Sits with the status badge rather than in the sub-line: it qualifies how
    # far the status can be trusted, which is the same question the badge
    # answers, and a reader scanning the list reads those two together.
    verified = confirmed.pill(p, e, full_date)

    note = f'<p class="fac-note">{e(p["note"])}</p>' if p.get("note") else ""
    quote = (f'<p class="fac-quote">“{e(p["sourceQuote"])}”</p>'
             if p.get("sourceQuote") else "")
    checked = (f'<span class="fac-checked">Checked {e(p["checked"])}</span>'
               if p.get("checked") else "")

    # id gives every program a direct anchor, so a search that lands on this
    # page can be pointed at the right entry
    return (
        f'<li class="fac-card" id="program-{e(p["id"])}">'
        '<div class="fac-head"><div>'
        f'<h3>{e(p["school"])}</h3>'
        f'<p class="fac-sub">{sub}</p>'
        '</div>'
        f'<div class="fac-head-right">{star_button(p)}{watch_button(p)}'
        f'{verified}{badge}</div>'
        '</div>'
        + app_info(p)
        + name_list(p.get("accepting"), "yes", "Accepting students")
        + name_list(p.get("maybe"), "maybe", "Undecided — contact directly")
        + name_list(p.get("notAccepting"), "no", "Not accepting this cycle")
        + note + quote
        + '<div class="fac-foot">'
        f'<a href="../programs/{e(p["id"])}.html">Full entry →</a>'
        f'<a href="{e(p.get("url"))}" target="_blank" rel="noopener">'
        'Check the program’s own page →</a>'
        f'{checked}</div></li>'
    )


def replace_between(text, start, end, payload):
    if start in text and end in text:
        pre = text.split(start)[0]
        post = text.split(end, 1)[1]
        return pre + start + payload + end + post
    # first run: swap the loading placeholder for the generated block
    placeholder = re.search(
        r'([ \t]*)<li class="fac-empty">Loading programs[^<]*</li>', text)
    if not placeholder:
        raise SystemExit("render_tracker: could not find the list placeholder "
                         "or the markers in " + PAGE)
    indent = placeholder.group(1)
    return text.replace(placeholder.group(0),
                        f"{indent}{start}{payload}{indent}{end}")


# The cycle year appears in the title, the H1, the visible heading and the
# social cards. Retyping it in five places once a year is how a tracker ends
# up advertising last cycle, so it is written from programs.json instead --
# which keeps the brief's rule that this page keeps one URL forever and only
# the year changes.
CYCLE = re.compile(r"Fall\s+\d{4}")
CYCLE_ELEMENTS = [
    r"(<title>)(.*?)(</title>)",
    r"(<meta name=\"description\" content=\")(.*?)(\">)",
    r"(<meta property=\"og:title\" content=\")(.*?)(\">)",
    r"(<meta property=\"og:description\" content=\")(.*?)(\">)",
    r"(<h1 class=\"visually-hidden\">)(.*?)(</h1>)",
    r"(<h2>Who's Accepting Doctoral Students)(.*?)(</h2>)",
]


def set_cycle(text, cycle):
    if not CYCLE.fullmatch(cycle or ""):
        return text  # an unexpected cycle string is left alone rather than guessed at
    for pat in CYCLE_ELEMENTS:
        text = re.sub(pat,
                      lambda m: m.group(1) + CYCLE.sub(cycle, m.group(2)) + m.group(3),
                      text, count=1, flags=re.S)
    # the lede's cycle, which the script also fills in on load
    return re.sub(r'(<(?:span|strong|em|b)[^>]*id="fac-cycle"[^>]*>).*?(</(?:span|strong|em|b)>)',
                  lambda m: m.group(1) + e(cycle) + m.group(2), text, count=1, flags=re.S)


def freshen_updated(data):
    """Derive the "last updated" date instead of trusting a typed one.

    It was a hand-maintained field, so it did what hand-maintained fields do:
    a full sweep updated twelve programs and the page still announced the date
    of the sweep before it. The newest per-program `checked` date is the honest
    answer and cannot drift. Written back to the file so js/faculty.js, which
    renders the same line for readers with JavaScript, agrees with the HTML."""
    newest = max((p["checked"] for p in data["programs"] if p.get("checked")),
                 default=data.get("updated", ""))
    if newest and newest != data.get("updated"):
        data["updated"] = newest
        with open(DATA, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=1, ensure_ascii=False)
            f.write("\n")
    return newest


def full_date(iso):
    """"September 18, 2026" — with the year, unlike day_label, because this
    one ends up in a tooltip that outlives the banner's three-week window."""
    y, m, d = (int(x) for x in iso.split("-"))
    return date(y, m, d).strftime("%B") + f" {d}, {y}"


def day_label(iso):
    """"September 8" — no year, since the banner only ever spans three weeks."""
    y, m, d = (int(x) for x in iso.split("-"))
    return date(y, m, d).strftime("%B") + f" {d}"


def set_banner_hidden(text, hidden, cutoff):
    """Toggle the banner's hidden attribute, in both directions, and record the
    cutoff date this build used.

    The previous version only ever stripped `hidden`, so once anything had been
    newly posted the banner could not turn itself off again: the attribute was
    gone from the file and there was nothing left to strip. Normalising first
    and re-adding makes it idempotent whichever way it needs to go.

    The cutoff is published into the markup because js/faculty.js re-decides
    whether this banner should be shown, and it used to derive the cutoff from
    the reader's clock while this file derived it from the build's. Those agree
    right up until the build goes a day stale, and then they disagree -- the
    script hides a banner the server had shown, and everything below it jumps
    up a moment after the page loads. The banner sits above a 257-card list, so
    that is a whole-page shift, which is the shape of the CLS attributed to
    <body> in the field data. Handing the browser this date means the two can
    still both be out of date, but they can no longer be out of date
    differently."""
    text = re.sub(r'(<div class="fac-new-banner" id="fac-new-banner")'
                  r'(?:\s+data-cutoff="[^"]*")?(?:\s+hidden)?(\s*>)',
                  r"\1\2", text, count=1)
    attrs = f' data-cutoff="{e(cutoff)}"' + (" hidden" if hidden else "")
    return re.sub(r'(<div class="fac-new-banner" id="fac-new-banner")(\s*>)',
                  lambda m: m.group(1) + attrs + m.group(2), text, count=1)


def render():
    data = json.load(open(DATA, encoding="utf-8"))
    freshen_updated(data)
    programs = sorted(data["programs"], key=lambda p: p["school"].lower())
    posted = [p for p in programs if p["status"] == "posted"]
    faculty = sum(len(p.get("accepting") or []) for p in posted)

    text = open(PAGE, encoding="utf-8").read()
    cards = "\n" + "\n".join(card(p) for p in programs) + "\n"
    text = replace_between(text, START, END, cards)
    text = set_cycle(text, data.get("cycle", ""))

    # the same three lines the script fills in on load, so they are also
    # present for a crawler that never runs it
    stats = (f'<strong>{faculty}</strong> faculty confirmed accepting across '
             f'<strong>{len(posted)}</strong> programs · last updated '
             f'{e(data.get("updated", ""))}')
    text = re.sub(r'(<p class="fac-stats" id="fac-stats">).*?(</p>)',
                  lambda m: m.group(1) + stats + m.group(2), text, count=1, flags=re.S)

    showing = f"Showing {len(programs)} of {len(programs)} programs checked so far"
    text = re.sub(r'(<p class="fac-showing" id="fac-showing">).*?(</p>)',
                  lambda m: m.group(1) + showing + m.group(2), text, count=1, flags=re.S)

    # Only postings still inside the window count as news.
    cutoff = (date.today() - timedelta(days=NEWLY_WINDOW_DAYS)).isoformat()
    # Newest first, then alphabetical inside a date. Sorting the whole list
    # alphabetically buried the day's postings among ones three weeks old:
    # three programs posted on the 17th and sat between Arizona State and
    # Purdue from the 8th, so nothing on the page said anything had happened
    # today. js/faculty.js sorts identically -- if the two disagreed the list
    # would visibly reorder a moment after the page loaded.
    # Two stable passes: alphabetical, then newest date first. Sorting by name
    # and date together needs one field reversed and the other not, which a
    # single key cannot express for strings; sorting twice can, because Python's
    # sort is stable and the second pass preserves the first inside each date.
    recent = [(p["newlyPostedOn"], p["school"]) for p in programs
              if p.get("newlyPostedOn") and p["newlyPostedOn"] >= cutoff]
    recent.sort(key=lambda pair: pair[1].lower())
    recent.sort(key=lambda pair: pair[0], reverse=True)
    new = [school for _, school in recent]

    text = set_banner_hidden(text, not recent, cutoff)
    if recent:
        since = day_label(min(d for d, _ in recent))
        text = re.sub(r'(<strong id="fac-new-label">).*?(</strong>)',
                      lambda m: m.group(1) + f"Newly posted since {since}:" + m.group(2),
                      text, count=1, flags=re.S)
        # Separated with a middle dot, not a comma: "University of California,
        # Berkeley" and "University of Massachusetts, Boston" both contain
        # commas, so a comma-joined list read as nine schools instead of six.
        text = re.sub(r'(<span id="fac-new-schools">).*?(</span>)',
                      lambda m: m.group(1) + " &middot; ".join(e(s) for s in new) + m.group(2),
                      text, count=1, flags=re.S)
    else:
        text = re.sub(r'(<span id="fac-new-schools">).*?(</span>)',
                      lambda m: m.group(1) + m.group(2), text, count=1, flags=re.S)

    open(PAGE, "w", encoding="utf-8").write(text)
    return {"programs": len(programs), "posted": len(posted), "faculty": faculty,
            "newly": len(new)}


if __name__ == "__main__":
    r = render()
    print(f"tracker pre-rendered: {r['programs']} programs, "
          f"{r['faculty']} faculty across {r['posted']} posted")
