# -*- coding: utf-8 -*-
"""Write the professor list into its HTML at build time.

The page held 2,640 faculty, every one read from their own bio page, and
shipped 1,365 characters of visible text: a search box and "Loading
professors...". Every name arrived by JavaScript after load, so as far as
search was concerned none of them existed -- on the page most likely to be
searched for by name. It is the same problem the tracker had, on five times
as many names.

Two decisions worth knowing about, because both were measured rather than
assumed:

  Interests are not pre-rendered, past the first FULL_CARDS of them. With all
  of them the block is 268KB gzipped; with names, school and program alone it
  is 108KB, which is the tracker's 79KB in the same ballpark. The names are
  what people search; the interests are what the search box filters on and stay
  in the JSON for it. Topic pages are the right place for interests as
  crawlable text, because there they are grouped by subject instead of
  scattered across 2,640 cards.

  The exception is the first screenful, which ships complete because those are
  the cards a reader is looking at while the script fills the rest in, and
  growing them under the reader is what put this page at CLS 1.013. See
  FULL_CARDS.

  The accepting/not-accepting badge is not pre-rendered either. Resolving a
  program's list of names to a professor record needs the fuzzy matcher in
  js/professor-search.js -- "Denise Chavira" on the program page against
  "Denise A. Chavira" here -- and an exact-match version of it in Python
  resolved only 78%, which would have silently shown 111 accepting professors
  as unknown and disagreed with what the script renders a moment later. The
  tracker already carries that status as crawlable text; each card here links
  to the right entry on it instead, so the answer is one click away and stated
  in one place.

Called from build.py. Safe to re-run: it replaces everything between the
markers.
"""
import html
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
DATA = os.path.join(SITE, "data", "professors.json")
PROGRAMS = os.path.join(SITE, "data", "programs.json")
PAGE = os.path.join(SITE, "tools", "professor-search.html")
STARMAP = os.path.join(SITE, "data", "star-map.json")

START = "<!-- professors:list start (generated by scripts/render_professors.py) -->"
END = "<!-- professors:list end -->"


def e(s):
    return html.escape(str(s if s is not None else ""), quote=True)


# How many cards ship complete, with their interests and star button.
#
# A layout shift only counts against CLS if it happens inside the viewport, so
# the cards that grow when js/professor-search.js fills them are free as long
# as they are below the fold. These are not: they are the ones on screen at
# first paint, and they are why the page measured 1.013.
#
# 12 covers the tallest case -- a 900px phone viewport, whose cards are the
# narrowest and so the tallest, with .fac-head stacked into a column under
# 700px. A desktop screen fits fewer. Raising it is cheap (about 300 bytes
# gzipped each) but pointless; lowering it below what a tall phone shows puts
# the shift straight back.
FULL_CARDS = None   # None = every card. See below.

# Why every card now ships complete.
#
# Netlify cut the site off on 8 October 2026 for exceeding its bandwidth, and
# this page was the heaviest thing on it: 134KB of HTML plus 229KB of
# professors.json plus 79KB of programs.json, fetched on every single visit.
# 442KB to show a list the server could simply have sent.
#
# The earlier decision to ship lean cards compared HTML against HTML and
# ignored the JSON the page fetches regardless. Counting the whole visit,
# sending everything is lighter and it is one request instead of three.
#
# The badge was the thing blocking this. It needs each program's accepting
# list resolved to professor records, and an exact matcher in Python managed
# only 78%, so it was left to the fuzzy matcher in the browser. But
# data/star-map.json already holds that resolution, built at build time by
# render_starmap.py, and it reaches 685 of 714 -- the 29 it misses are names
# with no professor record at all, which the browser cannot badge either.

STATUS_LABEL = {
    "pending": "List not posted yet",
    "unverified": "Not checked by us yet",
    "cohort": "Admits by cohort &mdash; no mentor list",
    "closed": "Program closed this cycle",
}


def status_index(programs, star_map):
    """professor id -> accepting | maybe | not-accepting, for posted programs.

    The same thing js/professor-search.js builds at run time, built once here
    instead. star_map resolves a program's written name to a professor record;
    it is the output of the matching that could not be done in Python before.
    """
    out = {}
    for rec in programs:
        if rec.get("status") != "posted":
            continue
        for field, status in (("accepting", "accepting"),
                              ("maybe", "maybe"),
                              ("notAccepting", "not-accepting")):
            for name in (rec.get(field) or []):
                pid = star_map.get(
                    f"{rec['school']}|||{rec['program']}|||{name}")
                if pid:
                    out[pid] = status
    return out


def badge(p, prog, status):
    """Byte-for-byte what acceptingBadge() produced in the browser."""
    if not prog:
        return ""
    if prog.get("status") != "posted":
        label = STATUS_LABEL.get(prog.get("status"))
        return (f'<span class="fac-badge {e(prog["status"])}">{label}</span>'
                if label else "")
    if status == "accepting":
        return ('<span class="fac-check" '
                'title="Accepting doctoral students this cycle" '
                'aria-label="Accepting doctoral students this cycle">'
                '&#10003;</span>'
                '<span class="fac-badge posted">Accepting this cycle</span>')
    if status == "maybe":
        return ('<span class="fac-badge pending">Maybe &mdash; contact '
                'directly</span>')
    if status == "not-accepting":
        return '<span class="fac-badge closed">Not accepting this cycle</span>'
    return ""


def full_card(p, program_id, prog=None, status=None):
    """The complete card, rendering-identical to cardInner() in professor-search.js.

    Not byte-identical -- this writes &middot; and &rarr; where the script
    writes the characters themselves -- but the parsed DOM has to match, because
    the script fills these cards in place a moment after paint and any
    difference in what it writes is a shift in the part of the page the reader
    is looking at. If you change one, change both."""
    interests = "".join(f"<li>{e(i)}</li>" for i in (p.get("interests") or []))
    # The script writes the separator only when there is a program to put after
    # it, so this cannot write one unconditionally.
    sub = e(p["school"]) + (f' &middot; {e(p["program"])}' if p.get("program") else "")
    tracker = (f'<a class="prof-tracker-link" '
               f'href="faculty-accepting-students.html#program-{e(program_id)}">'
               f'Accepting-students status &rarr;</a>' if program_id else "")
    checked = (f'<span class="fac-checked">Checked {e(p["checked"])}</span>'
               if p.get("checked") else "")
    # The star ships unsaved. js/saved.js repaints it from the reader's own list
    # once that has loaded, and a star changing from outline to solid does not
    # move anything.
    star = ('<button type="button" class="star-btn" '
            f'data-star-prof="{e(p["id"])}" aria-pressed="false" '
            'aria-label="Save to my list" title="Save to my list">'
            '&#9734;</button>')
    return (
        f'<li class="fac-card" id="prof-{e(p["id"])}">'
        '<div class="fac-head"><div>'
        f'<h3>{e(p["name"])}</h3>'
        f'<p class="fac-sub">{sub}</p>'
        '</div>'
        f'<div class="fac-head-right">{star}{badge(p, prog, status)}</div>'
        '</div>'
        f'<ul class="prof-interests">{interests}</ul>'
        '<div class="fac-foot">'
        f'<a href="{e(p.get("url"))}" target="_blank" rel="noopener">'
        'View their university page &rarr;</a>'
        f'{tracker}{checked}</div></li>'
    )


def card(p, program_id):
    # The tracker link is worth its bytes and the interests are not: measured
    # over all 2,640 cards, the link costs 18KB gzipped because the same URL
    # shape repeats and compresses away, while three interests per card cost
    # 120KB because every one is different prose.
    tracker = (f'<a class="prof-tracker-link" '
               f'href="faculty-accepting-students.html#program-{e(program_id)}">'
               f'Accepting-students status &rarr;</a>' if program_id else "")
    return (
        f'<li class="fac-card" id="prof-{e(p["id"])}">'
        '<div class="fac-head"><div>'
        f'<h3>{e(p["name"])}</h3>'
        f'<p class="fac-sub">{e(p["school"])} &middot; {e(p["program"])}</p>'
        '</div></div>'
        '<div class="fac-foot">'
        f'<a href="{e(p.get("url"))}" target="_blank" rel="noopener">'
        'View their university page &rarr;</a>'
        f'{tracker}</div></li>'
    )


def replace_between(text, payload):
    if START in text and END in text:
        return (text.split(START)[0] + START + payload + END
                + text.split(END, 1)[1])
    placeholder = re.search(
        r'([ \t]*)<li class="fac-empty">Loading professors[^<]*</li>', text)
    if not placeholder:
        raise SystemExit("render_professors: could not find the list "
                         "placeholder or the markers in " + PAGE)
    indent = placeholder.group(1)
    return text.replace(placeholder.group(0),
                        f"{indent}{START}{payload}{indent}{END}")


def freshen_updated(data):
    """Derive "last updated" rather than trusting a typed one.

    Same trap as the tracker's: professors.json carried a hand-written date, so
    adding seven records on 14 September left the page still announcing 13
    August. The newest per-record `checked` date cannot drift. Written back so
    js/professor-search.js, which renders the same line, agrees with the HTML."""
    newest = max((p["checked"] for p in data["professors"] if p.get("checked")),
                 default=data.get("updated", ""))
    if newest and newest != data.get("updated"):
        data["updated"] = newest
        with open(DATA, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=1, ensure_ascii=False)
            f.write("\n")
    return newest


def render():
    data = json.load(open(DATA, encoding="utf-8"))
    freshen_updated(data)
    professors = sorted(data["professors"], key=lambda p: p["name"].lower())

    programs = json.load(open(PROGRAMS, encoding="utf-8"))["programs"]
    program_id = {(p["school"], p["program"]): p["id"] for p in programs}

    star_map = json.load(open(STARMAP, encoding="utf-8")).get("map", {})
    by_school_program = {(r["school"], r["program"]): r for r in programs}
    status_by_prof = status_index(programs, star_map)

    cards, linked, full, badged = [], 0, 0, 0
    for i, p in enumerate(professors):
        pid = program_id.get((p["school"], p["program"]))
        linked += bool(pid)
        prog = by_school_program.get((p["school"], p["program"]))
        status = status_by_prof.get(p["id"])
        if FULL_CARDS is None or i < FULL_CARDS:
            full += 1
            badged += bool(badge(p, prog, status))
            cards.append(full_card(p, pid, prog, status))
        else:
            cards.append(card(p, pid))

    text = open(PAGE, encoding="utf-8").read()
    text = replace_between(text, "\n" + "\n".join(cards) + "\n")

    schools = len({p["school"] for p in professors})
    stats = (f'<strong>{len(professors)}</strong> professors across '
             f'<strong>{schools}</strong> programs &middot; last updated '
             f'{e(data.get("updated", ""))}')
    text = re.sub(r'(<p class="fac-stats" id="prof-stats">).*?(</p>)',
                  lambda m: m.group(1) + stats + m.group(2),
                  text, count=1, flags=re.S)

    # The title and description are written here rather than left in the file
    # because both carry the professor count, and a number typed into the HTML
    # goes wrong the first time a sweep adds anybody.
    #
    # The old title was "Find a Professor by Research Interest", which never
    # said clinical psychology anywhere -- the <h1> did, but the title is the
    # stronger signal and it was the one page on the site not leading with the
    # field. Every sibling does: "Clinical Psychology Programs Accepting
    # Students", "Clinical Psychology Professors by Research Topic". This one
    # was the odd one out, and it is also the one that has yet to earn a click.
    count = f"{len(professors):,}"
    title = (f"Search {count} Clinical Psychology Professors by "
             f"Research Interest")
    # Kept under ~165 characters, which is about where Google stops showing a
    # description, and deliberately free of apostrophes: e() escapes them to
    # &#x27; inside the attribute, which is valid but reads badly in the source
    # next to every other description on the site.
    desc = (f"Search {count} clinical psychology faculty across {schools} "
            f"programs by what they research, each interest quoted from their "
            f"own university page, with accepting-students status.")
    og_desc = (f"Search {count} clinical psychology faculty by what they "
               f"research, quoted from their own university page.")

    text = re.sub(r"(<title>).*?(</title>)",
                  lambda m: m.group(1) + e(title) + m.group(2),
                  text, count=1, flags=re.S)
    text = re.sub(r'(<meta name="description" content=")[^"]*(")',
                  lambda m: m.group(1) + e(desc) + m.group(2), text, count=1)
    text = re.sub(r'(<meta property="og:title" content=")[^"]*(")',
                  lambda m: m.group(1) + e(title) + m.group(2), text, count=1)
    text = re.sub(r'(<meta property="og:description" content=")[^"]*(")',
                  lambda m: m.group(1) + e(og_desc) + m.group(2), text, count=1)

    open(PAGE, "w", encoding="utf-8").write(text)
    return {"professors": len(professors), "schools": schools, "linked": linked,
            "full": full, "badged": badged}


if __name__ == "__main__":
    r = render()
    print(f"professors pre-rendered: {r['professors']} across {r['schools']} "
          f"programs, {r['linked']} linked to a tracker entry, "
          f"{r['full']} shipped complete, {r['badged']} with a status badge")
